import type { Issue, Announcement, LostFoundItem, Comment, User, DashboardStats } from '@/types';

const mockReporter: User = {
  id: '1',
  email: 'student@hostel.edu',
  name: 'Rahul Sharma',
  role: 'student',
  hostel: 'Krishna Hostel',
  block: 'A',
  room: '204',
  createdAt: new Date('2024-01-15'),
};

const mockAssignee: User = {
  id: '3',
  email: 'caretaker@hostel.edu',
  name: 'Suresh Kumar',
  role: 'management',
  hostel: 'Krishna Hostel',
  block: 'All',
  room: 'Maintenance',
  createdAt: new Date('2022-03-10'),
};

const mockAdmin: User = {
  id: '2',
  email: 'admin@hostel.edu',
  name: 'Dr. Priya Patel',
  role: 'management',
  hostel: 'Krishna Hostel',
  block: 'Admin',
  room: 'Office',
  createdAt: new Date('2023-06-01'),
};

export const mockIssues: Issue[] = [
  {
    id: '1',
    title: 'Water leakage in bathroom ceiling',
    description: 'There is continuous water dripping from the bathroom ceiling near the shower area. The paint is also peeling off. This has been happening for the past 3 days.',
    category: 'plumbing',
    priority: 'high',
    status: 'in_progress',
    visibility: 'public',
    reporterId: '1',
    reporter: mockReporter,
    assigneeId: '3',
    assignee: mockAssignee,
    hostel: 'Krishna Hostel',
    block: 'A',
    room: '204',
    media: [],
    upvotes: 12,
    hasUpvoted: false,
    commentsCount: 5,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-21'),
    statusHistory: [
      { id: '1', status: 'reported', changedBy: mockReporter, changedAt: new Date('2024-01-20') },
      { id: '2', status: 'assigned', remarks: 'Assigned to maintenance team', changedBy: mockAdmin, changedAt: new Date('2024-01-20T14:00:00') },
      { id: '3', status: 'in_progress', remarks: 'Plumber dispatched', changedBy: mockAssignee, changedAt: new Date('2024-01-21') },
    ],
  },
  {
    id: '2',
    title: 'WiFi not working in Block B',
    description: 'The WiFi has been extremely slow and disconnecting frequently in the entire Block B since yesterday morning. Unable to attend online classes.',
    category: 'internet',
    priority: 'emergency',
    status: 'assigned',
    visibility: 'public',
    reporterId: '1',
    reporter: { ...mockReporter, id: '4', name: 'Amit Verma', room: '312', block: 'B' },
    assigneeId: '3',
    assignee: { ...mockAssignee, name: 'IT Support Team' },
    hostel: 'Krishna Hostel',
    block: 'B',
    room: '312',
    media: [],
    upvotes: 45,
    hasUpvoted: true,
    commentsCount: 23,
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
    statusHistory: [
      { id: '1', status: 'reported', changedBy: mockReporter, changedAt: new Date('2024-01-22') },
      { id: '2', status: 'assigned', remarks: 'High priority - affecting multiple students', changedBy: mockAdmin, changedAt: new Date('2024-01-22T10:00:00') },
    ],
  },
  {
    id: '3',
    title: 'Broken chair in room',
    description: 'One of the study chairs has a broken leg and is unsafe to use. Need a replacement.',
    category: 'furniture',
    priority: 'low',
    status: 'resolved',
    visibility: 'public',
    reporterId: '1',
    reporter: mockReporter,
    hostel: 'Krishna Hostel',
    block: 'A',
    room: '204',
    media: [],
    upvotes: 2,
    hasUpvoted: false,
    commentsCount: 1,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-18'),
    resolvedAt: new Date('2024-01-18'),
    statusHistory: [
      { id: '1', status: 'reported', changedBy: mockReporter, changedAt: new Date('2024-01-15') },
      { id: '2', status: 'assigned', changedBy: mockAdmin, changedAt: new Date('2024-01-16') },
      { id: '3', status: 'in_progress', changedBy: mockAssignee, changedAt: new Date('2024-01-17') },
      { id: '4', status: 'resolved', remarks: 'Chair replaced', changedBy: mockAssignee, changedAt: new Date('2024-01-18') },
    ],
  },
  {
    id: '4',
    title: 'Cockroach infestation in corridor',
    description: 'Multiple cockroaches spotted in the corridor of Block C ground floor. Need pest control immediately.',
    category: 'pest_control',
    priority: 'high',
    status: 'reported',
    visibility: 'public',
    reporterId: '5',
    reporter: { ...mockReporter, id: '5', name: 'Sneha Gupta', room: '101', block: 'C' },
    hostel: 'Krishna Hostel',
    block: 'C',
    room: 'Corridor',
    media: [],
    upvotes: 18,
    hasUpvoted: false,
    commentsCount: 8,
    createdAt: new Date('2024-01-23'),
    updatedAt: new Date('2024-01-23'),
    statusHistory: [
      { id: '1', status: 'reported', changedBy: mockReporter, changedAt: new Date('2024-01-23') },
    ],
  },
  {
    id: '5',
    title: 'Electrical socket sparking',
    description: 'The socket near the study table is making sparking sounds when plugged in. Very dangerous!',
    category: 'electrical',
    priority: 'emergency',
    status: 'in_progress',
    visibility: 'private',
    reporterId: '1',
    reporter: mockReporter,
    assigneeId: '3',
    assignee: mockAssignee,
    hostel: 'Krishna Hostel',
    block: 'A',
    room: '204',
    media: [],
    upvotes: 0,
    commentsCount: 2,
    createdAt: new Date('2024-01-23'),
    updatedAt: new Date('2024-01-23'),
    statusHistory: [
      { id: '1', status: 'reported', changedBy: mockReporter, changedAt: new Date('2024-01-23') },
      { id: '2', status: 'assigned', remarks: 'URGENT - Safety hazard', changedBy: mockAdmin, changedAt: new Date('2024-01-23T09:00:00') },
      { id: '3', status: 'in_progress', remarks: 'Electrician en route', changedBy: mockAssignee, changedAt: new Date('2024-01-23T09:30:00') },
    ],
  },
];

export const mockAnnouncements: Announcement[] = [
  {
    id: '1',
    title: 'Water Supply Interruption',
    content: 'Due to maintenance work on the main water tank, water supply will be interrupted on 25th January from 10 AM to 2 PM. Please store water in advance.',
    type: 'maintenance',
    targetHostels: ['Krishna Hostel'],
    targetBlocks: ['A', 'B', 'C'],
    targetRoles: ['student', 'management'],
    author: mockAdmin,
    isPinned: true,
    expiresAt: new Date('2024-01-26'),
    createdAt: new Date('2024-01-23'),
    updatedAt: new Date('2024-01-23'),
  },
  {
    id: '2',
    title: 'Pest Control Drive',
    content: 'A comprehensive pest control drive will be conducted in all blocks on 28th January. Students are requested to keep their rooms accessible between 9 AM - 1 PM.',
    type: 'info',
    targetHostels: ['Krishna Hostel'],
    targetBlocks: ['A', 'B', 'C'],
    targetRoles: ['student'],
    author: mockAdmin,
    isPinned: false,
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: '3',
    title: 'Emergency: Power Outage in Block B',
    content: 'Block B is currently experiencing a power outage due to transformer issues. Electricians are working on it. Expected restoration: 2 hours.',
    type: 'urgent',
    targetHostels: ['Krishna Hostel'],
    targetBlocks: ['B'],
    targetRoles: ['student', 'management'],
    author: mockAdmin,
    isPinned: true,
    createdAt: new Date('2024-01-23'),
    updatedAt: new Date('2024-01-23'),
  },
  {
    id: '4',
    title: 'New Gym Hours',
    content: 'The hostel gym will now operate from 6 AM to 10 PM starting February 1st. Please carry your hostel ID for entry.',
    type: 'info',
    targetHostels: ['Krishna Hostel'],
    targetBlocks: ['A', 'B', 'C'],
    targetRoles: ['student'],
    author: mockAdmin,
    isPinned: false,
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
];

export const mockLostFound: LostFoundItem[] = [
  {
    id: '1',
    title: 'Blue JBL Bluetooth Earphones',
    description: 'Lost my blue JBL wireless earphones somewhere near the common room or canteen area.',
    status: 'lost',
    category: 'Electronics',
    location: 'Common Room / Canteen',
    date: new Date('2024-01-21'),
    images: [],
    reporterId: '1',
    reporter: mockReporter,
    createdAt: new Date('2024-01-22'),
    updatedAt: new Date('2024-01-22'),
  },
  {
    id: '2',
    title: 'Student ID Card - Amit Verma',
    description: 'Found a student ID card near the water cooler on 2nd floor Block A.',
    status: 'found',
    category: 'Documents',
    location: 'Block A, 2nd Floor',
    date: new Date('2024-01-23'),
    images: [],
    reporterId: '3',
    reporter: mockAssignee,
    createdAt: new Date('2024-01-23'),
    updatedAt: new Date('2024-01-23'),
  },
  {
    id: '3',
    title: 'Black Laptop Bag',
    description: 'Found a black laptop bag (HP brand) in the study hall. Contains some notebooks.',
    status: 'claimed',
    category: 'Bags',
    location: 'Study Hall',
    date: new Date('2024-01-19'),
    images: [],
    reporterId: '3',
    reporter: mockAssignee,
    claimedById: '5',
    claimedBy: { ...mockReporter, id: '5', name: 'Sneha Gupta' },
    claimedAt: new Date('2024-01-20'),
    createdAt: new Date('2024-01-19'),
    updatedAt: new Date('2024-01-20'),
  },
];

export const mockComments: Comment[] = [
  {
    id: '1',
    content: 'I have the same issue in room 205. The water pressure is also very low.',
    author: { ...mockReporter, id: '6', name: 'Vikram Singh', room: '205' },
    issueId: '1',
    reactions: [
      { type: 'like', count: 3, hasReacted: false },
      { type: 'helpful', count: 1, hasReacted: true },
      { type: 'urgent', count: 2, hasReacted: false },
    ],
    createdAt: new Date('2024-01-20T16:00:00'),
    updatedAt: new Date('2024-01-20T16:00:00'),
  },
  {
    id: '2',
    content: 'Plumber has been informed. Will update once fixed.',
    author: mockAssignee,
    issueId: '1',
    reactions: [
      { type: 'like', count: 5, hasReacted: true },
      { type: 'helpful', count: 8, hasReacted: false },
      { type: 'urgent', count: 0, hasReacted: false },
    ],
    createdAt: new Date('2024-01-21T09:00:00'),
    updatedAt: new Date('2024-01-21T09:00:00'),
  },
];

export const mockDashboardStats: DashboardStats = {
  totalIssues: 156,
  pendingIssues: 23,
  resolvedIssues: 133,
  avgResolutionTime: 48, // hours
  issuesByCategory: [
    { category: 'plumbing', count: 45 },
    { category: 'electrical', count: 32 },
    { category: 'internet', count: 28 },
    { category: 'cleanliness', count: 22 },
    { category: 'furniture', count: 15 },
    { category: 'pest_control', count: 8 },
    { category: 'security', count: 4 },
    { category: 'other', count: 2 },
  ],
  issuesByHostel: [
    { hostel: 'Krishna Hostel', count: 68 },
    { hostel: 'Radha Hostel', count: 45 },
    { hostel: 'Ganga Hostel', count: 43 },
  ],
  issuesByPriority: [
    { priority: 'low', count: 45 },
    { priority: 'medium', count: 67 },
    { priority: 'high', count: 38 },
    { priority: 'emergency', count: 6 },
  ],
  recentTrend: [
    { date: '2024-01-17', reported: 12, resolved: 8 },
    { date: '2024-01-18', reported: 8, resolved: 11 },
    { date: '2024-01-19', reported: 15, resolved: 9 },
    { date: '2024-01-20', reported: 10, resolved: 14 },
    { date: '2024-01-21', reported: 7, resolved: 12 },
    { date: '2024-01-22', reported: 18, resolved: 10 },
    { date: '2024-01-23', reported: 5, resolved: 8 },
  ],
};
